### ISSUE TITLE
problem with export to glb

### ISSUE THREAD

**Issue by yiming-cc** [Meshcapade/SMPL_blender_addon#13]
I added human body to blender using smplx add-on and change its body pose with pose mode. And I hope to export the customized human model to glb file. I successfully done the exportation but when I import it to blender again, the customized body pose I have done disappear, it came back to the template pose. But when I export it to obj and load and export to glb again, it works. Why would this happen? Thanks for your answer.

**Comment by nathan-meshcapade** [comment]
Hi, I tested this and it works for me.  There are two things I'd check:

1) Check and make sure that you are setting keyframes on the pose.  If you use the `load pose` button, it will automatically add a keyframe.  If you pose it by hand, blender expects you to add the keyframes yourself.  I made a short [video](https://github.com/Meshcapade/SMPL_blender_addon/assets/123560441/516c20cd-308e-4f94-b164-34431087dbaa) to show how to do this.

2)  Make sure that your glb export settings have animation export selected.  
These are my glb settings that worked for me:
![image](https://github.com/Meshcapade/SMPL_blender_addon/assets/123560441/1de5ac2b-97fb-43e7-8107-4dd3673145f4)
