### ISSUE TITLE
How to get pose parameters as a file

### ISSUE THREAD

**Issue by JosephKKim** [Meshcapade/SMPL_blender_addon#3]
Hi thanks for sharing nice work!! 
SMPL models are wonderful!

Since there is Write Pose to Console button in the add-on, I want to make it into a file.
But I'm new to Blender... so can you please tell me how to make list pose into a file? Is there a way to access to pose parameters 
by using console?

Thanks in advance!

**Comment by btparker** [comment]
Hello! 
[This pull request](https://github.com/Meshcapade/SMPL_blender_addon/pull/4) is to address this issue, allowing a user to save pose to file and be able to load that pose.

**Comment by btparker** [comment]
[Merged!](https://github.com/Meshcapade/SMPL_blender_addon/pull/4)
