### ISSUE TITLE
Adding Additional Shape Components

### ISSUE THREAD

**Issue by nicholaslocascio** [Meshcapade/SMPL_blender_addon#5]
Currently the addon uses SMPL-X v1.1 with 10 shape and 10 expression components.

Can this be extended to the full 300 component shape space? I have SMPL-X models with > 10 shape components that I'd like to utilize in Blender.

Thanks!

**Comment by nathan-meshcapade** [comment]
@nicholaslocascio the latest version of SMPLX has all 300 shape components.  [sales@meshcapade.com](mailto:sales@meshcapade.com) can get you the latest data folder.
