### ISSUE TITLE
can export fbx which contains animation?

### ISSUE THREAD

**Issue by foocker** [Meshcapade/SMPL_blender_addon#6]
from video, we can generate avatar which  format is smplx, but contains move rotation sequence(BVH).

**Comment by nathan-meshcapade** [comment]
The way to import BVH files into blender is to go to Edit > Preferences > Add-Ons > search 'motion' 
then check the box for:  `Import-Export: BIOVision Motion Capture (BVH) format`

![image](https://github.com/Meshcapade/SMPL_blender_addon/assets/123560441/63d4de25-af9e-4fe7-b2e2-45cfb2a51929)
