### ISSUE TITLE
if it could add smpl-x model with  10 shape components(beta[10])

### ISSUE THREAD

**Issue by LebinDing749** [Meshcapade/SMPL_blender_addon#9]
I got a well rigged model, but if it could customize details like body shapes

**Comment by nathan-meshcapade** [comment]
Select the model, then select Object Data Properties, then you can change the individual shape parameters (Shape###).  You can also use the `Random Body Shape` and `Random Face Shape` buttons to quickly randomize the different shape parameters.  You can increase the multipliers to get more variation.  Contact sales@meshcapade.com to get the data folder if you don't have it already.

![image](https://github.com/Meshcapade/SMPL_blender_addon/assets/123560441/91f37b2b-ecca-4c68-b133-5d6ae3f8e035)
